import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ToastContainer />

        {/* Fixed Header */}
        <div className="fixed top-0 left-0 right-0 z-100 border-b border-white/30">
          <Header />
        </div>

        {/* Main content with top padding to avoid overlap */}
        <div className="pt-[59px]">
          {children}
        </div>
      </body>
    </html>
  );
}
